[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm prisma generate && pnpm build"

[deploy]
startCommand = "pnpm prisma migrate deploy && node dist/src/index.js"
healthcheckPath = "/docs"

[nixpacks]
nodeVersion = "20"